---
name: Deploy Lambda using SAM CLI - Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar as credenciais da AWS
      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Instalar o SAM CLI
      - name: Install SAM CLI
        run: |
          if ! command -v sam &> /dev/null; then
            echo "SAM CLI not found. Installing..."
            curl --silent --location https://github.com/aws/aws-sam-cli/releases/download/v1.73.0/aws-sam-cli-linux-x86_64.zip -o sam-cli.zip
            unzip sam-cli.zip -d sam-cli
            sudo ./sam-cli/install
          else
            echo "SAM CLI is already installed."
          fi

      # 4. Empacotar o aplicativo Lambda com o SAM
      - name: Package SAM Application
        run: |
          sam build

      # 5. Fazer o deploy do Lambda
      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --stack-name lambda-demo --capabilities CAPABILITY_IAM --s3-bucket lambda-demo-devops

      # 6. (Opcional) Verifique o status após o deploy
      - name: Verify Lambda Deployment
        run: |
          aws lambda get-function --function-name lambda-demo
