---
name: Deploy Lambda using SAM CLI - Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar as credenciais da AWS
      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      # 3. Instalar o SAM CLI
      - name: Install SAM CLI
        run: |
          if ! command -v sam &> /dev/null; then
            echo "SAM CLI not found. Installing..."
            curl --silent --location https://github.com/aws/aws-sam-cli/releases/download/v1.73.0/aws-sam-cli-linux-x86_64.zip -o sam-cli.zip
            unzip sam-cli.zip -d sam-cli
            sudo ./sam-cli/install
          else
            echo "SAM CLI is already installed."
          fi

      # 4. Empacotar o aplicativo Lambda com o SAM
      - name: Package SAM Application
        run: |
          sam build

      # 5. Fazer o deploy do Lambda
      - name: Deploy SAM Application
        run: |
          python3 deploy.py dev